[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
cercols = "FjZVUx8ergLAEaB1Mucqizhk9XtQTZpnAffS5FBT2h4c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/matt/.config/solana/id.json"

[test.validator]
url = "https://mainnet.helius-rpc.com/?api-key=530a62d7-365f-40e6-bbb6-6572225f85ce"

# mpl-token-metadata
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

# mpl_token_auth_rules
[[test.validator.clone]]
address = "auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg"

# Critters Cult - Mint Account
[[test.validator.clone]]
address = "EGUZ1sDcA36amdE7KBHe2JRSTCRdM48PiJ6ZVX6PcL4D"

# Critters Cult - Token Account
[[test.validator.clone]]
address = "5ad2gME71CcTyP61zx3gqmKF2wsHvAsDdAyeEC2dBNPX"

# Critters Cult - Edition Account
[[test.validator.clone]]
address = "2HQrHAZXc81UUFjSNs45prxiu9PPaJqVjYKu26UpLm9E"

# Critters Cult - Metadata Account
[[test.validator.clone]]
address = "Ewo9HX1gdHC4nwVQ8bRw9Bu1NRLZpuSK8dwjjvSBEYBS"

# Critters Cult - Collection Account
[[test.validator.clone]]
address = "CKPYygUZ9aA4JY7qmyuvxT67ibjmjpddNtHJeu1uQBSM"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test_watch = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 -w --watch-files tests/**/*.ts"
